puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************"):w
    :q

    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");int title_screen()
{
    puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");
    puts("");
puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");


    puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");
    puts("");

    puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");
    puts("");

    puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");
    puts("");

    puts("*******************");
    puts("* PHS's Lovestory *");
    puts("*******************");

    return 0;
}

int main()
{
    title_screen();
    return 0;
}
